// DEV ONLY — this file must never be imported unconditionally in feature code.
// Always import via: if (import.meta.env.DEV) { const { MOCK_VIDEOS } = await import('@libs/utils/mock-data'); }
// or use the ?dev query alias in vite.config.ts.

import type { Video, Channel, Comment } from '@core/types';

export const CHANNELS: readonly Channel[] = [
  { id:'c1',  name:'Fireship',         handle:'@Fireship',      avatarInitials:'F',  subscriberCount:'3.1M',  subscriberRaw:3100000,  videoCount:412,  verified:true,  bannerGradient:'linear-gradient(135deg,#1a1a2e,#16213e)',  description:'Code reports and fast-paced tutorials for developers. New video every week.',  joinedDate:'Mar 2017', totalViews:'450M' },
  { id:'c2',  name:'Marques Brownlee', handle:'@mkbhd',         avatarInitials:'MB', subscriberCount:'18.6M', subscriberRaw:18600000, videoCount:1600, verified:true,  bannerGradient:'linear-gradient(135deg,#0a0a0a,#1a0533)',  description:'Quality tech videos for the top 1%. New video every week.',                    joinedDate:'Mar 2009', totalViews:'4.2B' },
  { id:'c3',  name:'Linus Tech Tips',  handle:'@LinusTechTips', avatarInitials:'LT', subscriberCount:'15.9M', subscriberRaw:15900000, videoCount:6200, verified:true,  bannerGradient:'linear-gradient(135deg,#0d1117,#161b22)',  description:'PC building, reviews, and tech curiosity.',                                    joinedDate:'Nov 2008', totalViews:'6.1B' },
  { id:'c4',  name:'Kurzgesagt',       handle:'@kurzgesagt',    avatarInitials:'K',  subscriberCount:'22.2M', subscriberRaw:22200000, videoCount:200,  verified:true,  bannerGradient:'linear-gradient(135deg,#1b1b1b,#2d1b69)',  description:'Science in a nutshell. We explain complex ideas through beautiful animation.', joinedDate:'Jul 2013', totalViews:'2.8B' },
  { id:'c5',  name:'Veritasium',       handle:'@veritasium',    avatarInitials:'V',  subscriberCount:'16.1M', subscriberRaw:16100000, videoCount:310,  verified:true,  bannerGradient:'linear-gradient(135deg,#0f3460,#1a1a2e)',  description:'An element of truth. Science and engineering explainers.',                    joinedDate:'Sep 2011', totalViews:'2.3B' },
  { id:'c6',  name:'The Verge',        handle:'@TheVerge',      avatarInitials:'TV', subscriberCount:'3.4M',  subscriberRaw:3400000,  videoCount:4800, verified:true,  bannerGradient:'linear-gradient(135deg,#1a0000,#3d0c02)',  description:'Tech, science, art, and culture. The future is arriving.',                    joinedDate:'Jan 2012', totalViews:'1.1B' },
  { id:'c7',  name:'Google',           handle:'@Google',        avatarInitials:'G',  subscriberCount:'9.0M',  subscriberRaw:9000000,  videoCount:3200, verified:true,  bannerGradient:'linear-gradient(135deg,#1a1a2e,#0f3460)',  description:'The official Google YouTube channel.',                                        joinedDate:'Nov 2005', totalViews:'1.8B' },
  { id:'c8',  name:'NASA',             handle:'@NASA',          avatarInitials:'N',  subscriberCount:'10.1M', subscriberRaw:10100000, videoCount:1800, verified:true,  bannerGradient:'linear-gradient(135deg,#0d1b2a,#1b263b)',  description:"Explore the universe with NASA. We're inviting you on a journey.",            joinedDate:'Oct 2005', totalViews:'2.1B' },
  { id:'c9',  name:'SpaceX',           handle:'@SpaceX',        avatarInitials:'SX', subscriberCount:'6.3M',  subscriberRaw:6300000,  videoCount:280,  verified:true,  bannerGradient:'linear-gradient(135deg,#0a0a0a,#1a1a1a)',  description:'Making life multiplanetary. Manifesting the future.',                         joinedDate:'Mar 2006', totalViews:'980M' },
  { id:'c10', name:'TechLinked',       handle:'@TechLinked',    avatarInitials:'TL', subscriberCount:'3.2M',  subscriberRaw:3200000,  videoCount:1100, verified:true,  bannerGradient:'linear-gradient(135deg,#16213e,#0f3460)',  description:'Fast-fire tech news. Every Monday, Wednesday, Friday.',                      joinedDate:'Jun 2017', totalViews:'620M' },
];

export const VIDEOS: readonly Video[] = [
  { id:'v1',  channelId:'c1',  title:'How GPT-4o Actually Works Under the Hood',                channelName:'Fireship',         channelHandle:'@Fireship',      channelVerified:true, channelAvatarInitials:'F',  thumbnailUrl:'https://picsum.photos/seed/gpt4o/640/360',           duration:'11:42', viewCount:'3.2M',  viewCountRaw:3200000,  publishedAgo:'2 days ago',   publishedAt:Date.now()-2*86400000,  likeCount:'142K', description:'A deep dive into GPT-4o architecture, multimodal fusion, attention mechanisms, and how OpenAI compressed the model for real-time performance.',     category:'AI',      tags:['All','AI','Tech'] },
  { id:'v2',  channelId:'c2',  title:'Every Flagship Smartphone of 2025 Ranked',                channelName:'Marques Brownlee', channelHandle:'@mkbhd',         channelVerified:true, channelAvatarInitials:'MB', thumbnailUrl:'https://picsum.photos/seed/phones25/640/360',        duration:'24:15', viewCount:'8.7M',  viewCountRaw:8700000,  publishedAgo:'5 days ago',   publishedAt:Date.now()-5*86400000,  likeCount:'380K', description:'MKBHD ranks every flagship smartphone of 2025 on camera, performance, battery, and value. Galaxy S25 Ultra, iPhone 17 Pro Max, Pixel 9 Pro and more.', category:'Reviews', tags:['All','Tech','Reviews'] },
  { id:'v3',  channelId:'c4',  title:'Why the Universe Will Never Be the Same After This',      channelName:'Kurzgesagt',       channelHandle:'@kurzgesagt',    channelVerified:true, channelAvatarInitials:'K',  thumbnailUrl:'https://picsum.photos/seed/universe25/640/360',      duration:'14:30', viewCount:'12.1M', viewCountRaw:12100000, publishedAgo:'1 week ago',   publishedAt:Date.now()-7*86400000,  likeCount:'710K', description:'Scientists discovered evidence that may overturn our understanding of dark matter entirely. We explore what this means for physics and cosmology.',       category:'Science', tags:['All','Science'] },
  { id:'v4',  channelId:'c3',  title:'We Built a Homelab Server Cluster for $500',              channelName:'Linus Tech Tips',  channelHandle:'@LinusTechTips', channelVerified:true, channelAvatarInitials:'LT', thumbnailUrl:'https://picsum.photos/seed/homelab/640/360',         duration:'33:08', viewCount:'5.4M',  viewCountRaw:5400000,  publishedAgo:'3 days ago',   publishedAt:Date.now()-3*86400000,  likeCount:'220K', description:'Building a full Kubernetes cluster using old hardware worth under $500. Can it actually run production workloads?',                                       category:'Tech',    tags:['All','Tech'] },
  { id:'v5',  channelId:'c5',  title:'The Hidden Physics Inside Every Black Hole',              channelName:'Veritasium',       channelHandle:'@veritasium',    channelVerified:true, channelAvatarInitials:'V',  thumbnailUrl:'https://picsum.photos/seed/blackhole/640/360',       duration:'19:22', viewCount:'9.8M',  viewCountRaw:9800000,  publishedAgo:'2 weeks ago',  publishedAt:Date.now()-14*86400000, likeCount:'490K', description:'The counterintuitive physics inside black holes — spaghettification, information paradoxes, and what Hawking radiation actually tells us.',                category:'Science', tags:['All','Science'] },
  { id:'v6',  channelId:'c6',  title:'Google I/O 2025: Every Announcement in 10 Minutes',      channelName:'The Verge',        channelHandle:'@TheVerge',      channelVerified:true, channelAvatarInitials:'TV', thumbnailUrl:'https://picsum.photos/seed/gio25/640/360',           duration:'10:05', viewCount:'4.2M',  viewCountRaw:4200000,  publishedAgo:'1 day ago',    publishedAt:Date.now()-1*86400000,  likeCount:'198K', description:'Every Google I/O 2025 announcement. Gemini 2.0 Ultra, Android 16, Google Glass 2, Project Astra updates, and everything else.',                       category:'Tech',    tags:['All','Tech','AI'] },
  { id:'v7',  channelId:'c7',  title:'Gemini 2.0 Ultra: Multimodal AI at Production Scale',    channelName:'Google',           channelHandle:'@Google',        channelVerified:true, channelAvatarInitials:'G',  thumbnailUrl:'https://picsum.photos/seed/gemini2/640/360',         duration:'8:57',  viewCount:'11.3M', viewCountRaw:11300000, publishedAgo:'4 days ago',   publishedAt:Date.now()-4*86400000,  likeCount:'330K', description:"Google's official introduction to Gemini 2.0 Ultra — real-time reasoning, 10M token context windows, native code execution and multimodal understanding.", category:'AI',      tags:['All','AI'] },
  { id:'v8',  channelId:'c9',  title:'Starship IFT-7: Full Booster Catch + Orbital Insertion', channelName:'SpaceX',           channelHandle:'@SpaceX',        channelVerified:true, channelAvatarInitials:'SX', thumbnailUrl:'https://picsum.photos/seed/starship7/640/360',       duration:'45:12', viewCount:'28.4M', viewCountRaw:28400000, publishedAgo:'1 week ago',   publishedAt:Date.now()-7*86400000,  likeCount:'1.2M', description:"SpaceX Starship IFT-7 — the first successful full Super Heavy catch by Mechazilla arms and Starship reaching stable orbit with complete mission success.", category:'Space',   tags:['All','Science','Space'] },
  { id:'v9',  channelId:'c10', title:'I Replaced My Mac With a $1000 Mini PC for 30 Days',    channelName:'TechLinked',       channelHandle:'@TechLinked',    channelVerified:true, channelAvatarInitials:'TL', thumbnailUrl:'https://picsum.photos/seed/minipc/640/360',          duration:'16:44', viewCount:'1.9M',  viewCountRaw:1900000,  publishedAgo:'6 days ago',   publishedAt:Date.now()-6*86400000,  likeCount:'87K',  description:'Can a $1000 AMD mini PC running Windows 11 truly replace a MacBook Pro M4 for everyday development and content creation? 30 day real-world test.',       category:'Reviews', tags:['All','Tech','Reviews'] },
  { id:'v10', channelId:'c1',  title:'JavaScript Just Changed Everything (Again)',             channelName:'Fireship',         channelHandle:'@Fireship',      channelVerified:true, channelAvatarInitials:'F',  thumbnailUrl:'https://picsum.photos/seed/js2025/640/360',          duration:'7:28',  viewCount:'2.6M',  viewCountRaw:2600000,  publishedAgo:'3 days ago',   publishedAt:Date.now()-3*86400000,  likeCount:'118K', description:'The 10 most impactful JavaScript features landing in 2025 — temporal API, records & tuples, pattern matching, explicit resource management and more.',    category:'Dev',     tags:['All','Tech','Dev'] },
  { id:'v11', channelId:'c8',  title:'How NASA is Building the Artemis Moon Base',             channelName:'NASA',             channelHandle:'@NASA',          channelVerified:true, channelAvatarInitials:'N',  thumbnailUrl:'https://picsum.photos/seed/artemis/640/360',         duration:'21:34', viewCount:'7.1M',  viewCountRaw:7100000,  publishedAgo:'2 weeks ago',  publishedAt:Date.now()-14*86400000, likeCount:'305K', description:'NASA engineers explain how the Artemis lunar base will be constructed using 3D printing, in-situ resource utilization, and modular habitat systems.',    category:'Space',   tags:['All','Science','Space'] },
  { id:'v12', channelId:'c4',  title:'The Neuroscience of Procrastination',                   channelName:'Kurzgesagt',       channelHandle:'@kurzgesagt',    channelVerified:true, channelAvatarInitials:'K',  thumbnailUrl:'https://picsum.photos/seed/procrastinate/640/360',   duration:'12:00', viewCount:'18.5M', viewCountRaw:18500000, publishedAgo:'3 weeks ago',  publishedAt:Date.now()-21*86400000, likeCount:'920K', description:"Why our brains evolved to avoid future tasks, and evidence-backed strategies to actually get things done. Based on the latest neuroscience research.",     category:'Science', tags:['All','Science'] },
  { id:'v13', channelId:'c5',  title:'The Largest Structure in the Universe',                  channelName:'Veritasium',       channelHandle:'@veritasium',    channelVerified:true, channelAvatarInitials:'V',  thumbnailUrl:'https://picsum.photos/seed/structure/640/360',       duration:'22:14', viewCount:'6.3M',  viewCountRaw:6300000,  publishedAgo:'1 month ago',  publishedAt:Date.now()-30*86400000, likeCount:'312K', description:'Exploring the Hercules-Corona Borealis Great Wall — the largest known structure in the observable universe, spanning 10 billion light-years.',            category:'Science', tags:['All','Science'] },
  { id:'v14', channelId:'c2',  title:'The M4 MacBook Air is Absurdly Good',                   channelName:'Marques Brownlee', channelHandle:'@mkbhd',         channelVerified:true, channelAvatarInitials:'MB', thumbnailUrl:'https://picsum.photos/seed/m4air/640/360',           duration:'18:32', viewCount:'14.2M', viewCountRaw:14200000, publishedAgo:'2 weeks ago',  publishedAt:Date.now()-14*86400000, likeCount:'640K', description:'The M4 MacBook Air — thinner, faster, and with better battery life than anything else at this price. Could this be the last laptop you ever need?',       category:'Reviews', tags:['All','Tech','Reviews'] },
  { id:'v15', channelId:'c3',  title:'This $200 GPU Destroyed My Expectations',               channelName:'Linus Tech Tips',  channelHandle:'@LinusTechTips', channelVerified:true, channelAvatarInitials:'LT', thumbnailUrl:'https://picsum.photos/seed/gpu200/640/360',          duration:'28:45', viewCount:'8.1M',  viewCountRaw:8100000,  publishedAgo:'4 days ago',   publishedAt:Date.now()-4*86400000,  likeCount:'390K', description:'Budget GPU shootout: does the $200 price point actually deliver in 2025? We test 1080p, 1440p, and ray tracing across 10 titles.',                        category:'Tech',    tags:['All','Tech','Reviews'] },
  { id:'v16', channelId:'c7',  title:'Building AI Agents That Actually Work',                  channelName:'Google',           channelHandle:'@Google',        channelVerified:true, channelAvatarInitials:'G',  thumbnailUrl:'https://picsum.photos/seed/aiagents/640/360',        duration:'32:18', viewCount:'5.7M',  viewCountRaw:5700000,  publishedAgo:'5 days ago',   publishedAt:Date.now()-5*86400000,  likeCount:'245K', description:'A technical deep dive into building reliable AI agents using Gemini — tool use, memory systems, multi-agent orchestration, and evaluation frameworks.',   category:'AI',      tags:['All','AI','Dev'] },
];

export const COMMENTS: readonly Comment[] = [
  { id:'cm1', authorName:'Alex Chen',         authorAvatarInitials:'AC', authorColor:'#4285F4', isPinned:true,  text:"This is honestly one of the best technical explanations I've seen. The animation quality is insane and the depth is just right.",                                              likeCount:'4.2K', publishedAgo:'3 days ago',   replyCount:48 },
  { id:'cm2', authorName:'Sarah M.',           authorAvatarInitials:'SM', authorColor:'#EA4335', isPinned:false, text:"I've watched this 3 times and still learn something new each time. The section on attention mechanisms finally clicked for me after years of confusion.",              likeCount:'2.8K', publishedAgo:'2 days ago',   replyCount:22 },
  { id:'cm3', authorName:'TechEnthusiast99',   authorAvatarInitials:'TE', authorColor:'#FBBC04', isPinned:false, text:'The way you broke down the architecture is incredible. Been trying to understand this for months — this video made everything click in 12 minutes.',               likeCount:'1.9K', publishedAgo:'1 day ago',    replyCount:15 },
  { id:'cm4', authorName:'Dr. Priya Sharma',   authorAvatarInitials:'PS', authorColor:'#34A853', isPinned:false, text:'As a researcher in this field, I can confirm this is surprisingly accurate for a YouTube video. Great job making it accessible without sacrificing correctness!', likeCount:'3.1K', publishedAgo:'4 days ago',   replyCount:31 },
  { id:'cm5', authorName:'coding_wizard',      authorAvatarInitials:'CW', authorColor:'#7C4DFF', isPinned:false, text:'Subscribed immediately after this. The production value combined with technical depth is genuinely rare on this platform. Keep it up.',                            likeCount:'987',  publishedAgo:'12 hours ago', replyCount:9  },
  { id:'cm6', authorName:'Marcus Rivera',      authorAvatarInitials:'MR', authorColor:'#FF6D00', isPinned:false, text:"I'm a senior ML engineer and I still picked up nuances I'd never thought about. The latency optimization section especially — mind blown.",                       likeCount:'1.4K', publishedAgo:'5 days ago',   replyCount:18 },
  { id:'cm7', authorName:'Yuki Tanaka',        authorAvatarInitials:'YT', authorColor:'#00BCD4', isPinned:false, text:"Finally a video that doesn't dumb things down. My university course spent 3 weeks on what you explained in 15 minutes, and yours was clearer.",                    likeCount:'2.2K', publishedAgo:'6 days ago',   replyCount:27 },
];

const COLORS = ['#4285F4','#EA4335','#FBBC04','#34A853','#FF6D00','#7C4DFF','#00BCD4','#F06292','#26A69A','#EC407A'];

export function avatarColor(seed: string): string {
  const hash = seed.split('').reduce((a, c) => a + c.charCodeAt(0), 0);
  return COLORS[hash % COLORS.length]!;
}

/** Format raw view count to YouTube-style string */
export function formatCount(n: number): string {
  if (n >= 1_000_000_000) return (n / 1_000_000_000).toFixed(1).replace(/\.0$/, '') + 'B';
  if (n >= 1_000_000)     return (n / 1_000_000).toFixed(1).replace(/\.0$/, '') + 'M';
  if (n >= 1_000)         return (n / 1_000).toFixed(0) + 'K';
  return String(n);
}
